# Generated by Django 4.2.4 on 2023-09-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Money', '0002_contenido_remove_publicacion_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='contenido',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='contenidos',
            field=models.ManyToManyField(to='Money.contenido'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='descripcion',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
