# Generated by Django 4.2.4 on 2023-09-12 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Money', '0003_remove_publicacion_contenido_publicacion_contenidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='likes',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
