# Generated by Django 4.2.4 on 2023-09-12 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Money', '0004_remove_publicacion_likes_publicacion_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
