# Generated by Django 4.2.4 on 2023-09-12 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Money', '0007_rename_usuario_tokenverificacioncorreo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='enlace_facebook',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='enlace_youtube',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='numero_seguidores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='numero_videos_publicados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='suscripcion_requerida',
            field=models.ForeignKey(blank=True, help_text='Tipo de suscripción necesaria para ver esta publicación.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Money.tiposuscripcion'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='activo', max_length=10),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='suscriptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tiposuscripcion',
            name='contenido_o_privilegios',
            field=models.TextField(blank=True, help_text='Descripción de lo que el suscriptor obtendrá con esta suscripción.', null=True),
        ),
        migrations.AddField(
            model_name='tiposuscripcion',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tiposuscripcion',
            name='duracion_dias',
            field=models.PositiveIntegerField(blank=True, help_text='Duración de la suscripción en días.', null=True),
        ),
        migrations.AddField(
            model_name='tiposuscripcion',
            name='es_recurrente',
            field=models.BooleanField(default=True, help_text='Indica si la suscripción se renueva automáticamente.'),
        ),
        migrations.AddField(
            model_name='tiposuscripcion',
            name='esta_aprobada',
            field=models.BooleanField(blank=True, default=False, help_text='Indica si esta suscripción ha sido aprobada para ser ofrecida a otros usuarios.', null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='categorias',
            field=models.ManyToManyField(blank=True, null=True, to='Money.categoria'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='dislikes',
            field=models.ManyToManyField(blank=True, null=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(blank=True, choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicado'), ('Archivado', 'Archivado')], default='Borrador', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, null=True, to='Money.etiqueta'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='visibilidad',
            field=models.CharField(blank=True, choices=[('Publico', 'Público'), ('Privado', 'Privado'), ('SoloAmigos', 'Solo Amigos'), ('Suscriptores', 'Solo Suscriptores')], default='Publico', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tiposuscripcion',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
