# Generated by Django 4.2.4 on 2023-09-14 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Money', '0008_remove_publicacion_tipo_remove_suscripcion_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupochat',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grupochat',
            name='enlace_invitacion',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='grupochat',
            name='foto_grupo',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_grupo/'),
        ),
        migrations.AddField(
            model_name='grupochat',
            name='mensaje_anclado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupo_anclado', to='Money.mensajeprivado'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='lista_amigos_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Amistad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_amistad', models.DateTimeField(auto_now_add=True)),
                ('es_aceptada', models.BooleanField(default=False)),
                ('usuario1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistades_iniciadas', to=settings.AUTH_USER_MODEL)),
                ('usuario2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistades_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
