# Generated by Django 4.2.4 on 2023-09-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Money', '0011_remove_contenido_leccion_alter_leccion_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
