# Generated by Django 4.2.4 on 2023-09-14 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Money', '0014_amigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeprivado',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Money.grupochat'),
        ),
    ]
