# Generated by Django 4.2.4 on 2023-09-15 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Money', '0015_alter_mensajeprivado_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='curso',
            name='categoria',
            field=models.CharField(choices=[('TransmisionEnVivo', 'Transmisión en vivo'), ('CursoEnLinea', 'Curso en línea')], default='CursoEnLinea', max_length=100),
        ),
        migrations.AddField(
            model_name='curso',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leccion',
            name='duracion',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leccion',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completado', 'Completado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=15),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='miniatura',
            field=models.ImageField(blank=True, null=True, upload_to='miniaturas/'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='tipo_publicacion',
            field=models.CharField(choices=[('ARTICULO', 'Artículo'), ('VIDEO', 'Video'), ('PODCAST', 'Podcast')], default='ARTICULO', max_length=100),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='categorias',
            field=models.ManyToManyField(to='Money.categoria'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='dislikes',
            field=models.ManyToManyField(related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicado'), ('Archivado', 'Archivado')], default='Borrador', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='etiquetas',
            field=models.ManyToManyField(to='Money.etiqueta'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='suscripcion_requerida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Money.tiposuscripcion'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='visibilidad',
            field=models.CharField(choices=[('Publico', 'Público'), ('Privado', 'Privado'), ('SoloAmigos', 'Solo Amigos'), ('Suscriptores', 'Solo Suscriptores')], default='Publico', max_length=20),
        ),
    ]
