# Generated by Django 4.2.4 on 2023-09-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Money', '0016_comentario_likes_curso_categoria_curso_destacado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='codigo_pais',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='numero_telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
