# Generated by Django 4.2.4 on 2023-09-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Money', '0018_curso_vistas_alter_curso_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='lecciones_completadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inscripcioncurso',
            name='progreso',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
