# Generated by Django 4.2.4 on 2023-10-20 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Money', '0021_remove_perfilusuario_foto_perfilusuario_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Money.curso'),
        ),
    ]
