# Generated by Django 4.2.4 on 2023-10-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Money', '0022_comentario_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcioncurso',
            name='completado',
            field=models.IntegerField(default=False),
        ),
    ]
