# Generated by Django 4.2.4 on 2023-10-17 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Money', '0023_pago_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleperfilusuario',
            name='cuenta_google',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_google', to=settings.AUTH_USER_MODEL),
        ),
    ]
