# Generated by Django 4.2.4 on 2023-10-21 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Money', '0023_alter_inscripcioncurso_completado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='curso',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Money.curso'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='publicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Money.publicacion'),
        ),
        migrations.CreateModel(
            name='CursoComprado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Money.curso')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Money.pago')),
            ],
        ),
    ]
