# Generated by Django 4.2.4 on 2023-10-17 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Money', '0024_detalleperfilusuario_cuenta_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleperfilusuario',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to=settings.AUTH_USER_MODEL),
        ),
    ]
