# Generated by Django 4.2.4 on 2023-10-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Money', '0024_alter_comentario_curso_alter_comentario_publicacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.ImageField(upload_to='imagenes/')),
            ],
        ),
    ]
