# Generated by Django 4.2.4 on 2023-10-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Money', '0025_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='id_canal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='token_acceso_youtube',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='token_actualizacion_youtube',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TransmisionEnVivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('id_transmision_youtube', models.CharField(max_length=255)),
                ('id_stream_youtube', models.CharField(max_length=255)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('proxima', 'Próxima'), ('en_vivo', 'En Vivo'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('perfil_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Money.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisTransmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_espectadores', models.PositiveIntegerField(default=0)),
                ('maximo_espectadores', models.PositiveIntegerField(default=0)),
                ('tiempo_visionado_promedio', models.PositiveIntegerField(default=0)),
                ('transmision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Money.transmisionenvivo')),
            ],
        ),
    ]
